name: 'My reusable action'
description: 'This is a reusable action'
runs:
  using: 'composite'
  steps:
    - name: 安装依赖和构建
      run: |
        cd $MESSAGE-$MY_VAR
        npm install
        npm run build
      shell: bash
    - name: 部署 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: $MESSAGE-build
        folder: $MESSAGE-build
