name: 'My reusable action'
description: 'This is a reusable action'
runs:
  using: 'composite'
  steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4
    - name: 安装依赖和构建
      run: |
        cd ${{ env.MESSAGE }}-${{ env.MY_VAR }}
        npm install
        npm run build
      shell: bash
    - name: 部署 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ env.MESSAGE }}-build
        folder: ${{ env.MESSAGE }}-build
