name: 构建react项目
on: push

permissions:
  contents: write

jobs:
  one-build:
    name: 01 build 工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 安装依赖和构建
        run: |
          cd 01-start
          npm install
          npm run build
      - name: 部署 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: 01-build
          folder: 01-build
  two-build:
    name: 02 build 工作
    runs-on: ubuntu-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 安装依赖和构建
        run: |
          cd 02-start
          npm install
          npm run build
      - name: 部署 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: 02-build
          folder: 02-build



