name: 构建react项目
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MESSAGE: ${{github.event.head_commit.message }}
      GH_TOKEN: ${{ github.token }}
    name: ${{ github.event.head_commit.message }} 工作
    steps:
      - name: 检查条件
        id: check
        run: |
          for i in {1..10};do
            if [ "0"+$i -eq $MESSAGE ];then
              echo "MESSAGE 是 $MESSAGE ，继续工作流"
              echo "result=true" >> $GITHUB_ENV
              break
            fi
          done
      - name: 读取仓库内容
        if : env.result == 'true'
        uses: actions/checkout@v4

      - name: 打包项目
        if : env.result == 'true'
        uses: ./.github/actions/build-action


