name: 构建react项目
on: push

permissions:
  contents: write
env:
    MESSAGE: ${{ github.event.head_commit.message }}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VAR: start
    if: "contains(github.event.head_commit.message, '01')"
    name: 01 build 工作
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4
      - name: 打包项目
        uses: ./.github/actions/build-action


