name: 打包13
on:
  workflow_dispatch:
    inputs:
      file-number:
        description: '选择要构建的文件编号'
        required: true
        default: '13'
        type: string
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取仓库内容
        uses: actions/checkout@v4
      - name: 设置node环境
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: 安装和打包前端依赖
        run: |
          cd 13-HTTP-Requests
          npm install
          npm run build

      - name: 安装和打包express依赖
        run: |
          cd 13-HTTP-Requests/backend
          npm install
          npm run build
      - name: 部署 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{inputs.file-number}}-build
          folder: ${{inputs.file-number}}-build
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.file-number}}-build
          path: ${{inputs.file-number}}-build
