name: 构建react项目
on: push

permissions:
  contents: write

jobs:
  one-build:
    runs-on: ubuntu-latest
    env:
      MY_VAR: start
      MESSAGE: ${{ github.event.head_commit.message }}
    if: "contains(github.event.head_commit.message, '01')"
    name: 01 build 工作
    steps:
      - name: Run my action
        uses: ./.github/actions/build-action
#  two-build:
#    if: "contains(github.event.head_commit.message, '02')"
#    name: 02 build 工作
#    runs-on: ubuntu-latest
#    steps:
#      - name: 读取仓库内容
#        uses: actions/checkout@v4
#      - name: 安装依赖和构建
#        run: |
#          cd 02-start
#          npm install
#          npm run build
#      - name: 部署 🚀
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: 02-build
#          folder: 02-build
#  three-build:
#    if: "contains(github.event.head_commit.message, '03')"
#    name: 03 build 工作
#    runs-on: ubuntu-latest
#    steps:
#      - name: 读取仓库内容
#        uses: actions/checkout@v4
#      - name: 安装依赖和构建
#        run: |
#          cd 03-practice
#          npm install
#          npm run build
#      - name: 部署 🚀
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: 03-build
#          folder: 03-build
#  four-build:
#    if: "contains(github.event.head_commit.message, '04')"
#    name: 04 build 工作
#    runs-on: ubuntu-latest
#    steps:
#      - name: 读取仓库内容
#        uses: actions/checkout@v4
#      - name: 安装依赖和构建
#        run: |
#          cd 04-styling
#          npm install
#          npm run build
#      - name: 部署 🚀
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: 04-build
#          folder: 04-build



